'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Slips7ream.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_acer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_acer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_adaptec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_adaptec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_ads_technologies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_ads_technologies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_advanced_micro_devices() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_advanced_micro_devices", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_afatech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_afatech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_asmedia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_asmedia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_asustek_computer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_asustek_computer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_avermedia_technologies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_avermedia_technologies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_bitland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_bitland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_brother() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_brother", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_canon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_canon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_compro_technology() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_compro_technology", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_conexant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_conexant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_creatix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_creatix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_dell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_dell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_elan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_elan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_emulex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_emulex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_epson() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_epson", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_fuji_xerox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_fuji_xerox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_gigabyte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_gigabyte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_hannspree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_hannspree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_hauppauge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_hauppauge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_hewlett_packard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_hewlett_packard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_ibm_corporation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_ibm_corporation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_icp_vortex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_icp_vortex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_intel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_intel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_knc_one() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_knc_one", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_konica_minolta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_konica_minolta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_kworld() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_kworld", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_kyocera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_kyocera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_lexmark_international() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_lexmark_international", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_logitech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_logitech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_lsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_lsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_lumanate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_lumanate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_microsoft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_microsoft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_nvidia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_nvidia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_nxp_semiconductors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_nxp_semiconductors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_oem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_oem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_oki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_oki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_oracle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_oracle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_panasonic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_panasonic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_pinnacle_systems() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_pinnacle_systems", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_promise_technology() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_promise_technology", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_qlogic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_qlogic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_qualcomm_atheros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_qualcomm_atheros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_ralink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_ralink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_realtek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_realtek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_ricoh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_ricoh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_samsung() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_samsung", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_savin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_savin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_sceptre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_sceptre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_sharp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_sharp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_silicon_integrated_systems_corp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_silicon_integrated_systems_corp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_sony() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_sony", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_synaptics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_synaptics", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_terratec_electronic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_terratec_electronic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_toshiba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_toshiba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_via_technologies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_via_technologies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_vidzmedia_pte_ltd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_vidzmedia_pte_ltd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_vixs_systems() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_vixs_systems", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company_xerox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_xerox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property copy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property delete() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property expander() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expander", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_administrative_tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_administrative_tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_application_development_features() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_application_development_features", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_asp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_asp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_asp_net() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_asp_net", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_basic_authentication() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_basic_authentication", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_cgi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_cgi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_chess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_chess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_client_certificate_mapping_authentication() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_client_certificate_mapping_authentication", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_client_for_nfs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_client_for_nfs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_common_http_features() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_common_http_features", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_configuration_apis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_configuration_apis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_content_compression() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_content_compression", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_custom_logging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_custom_logging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_default_document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_default_document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_digest_authentication() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_digest_authentication", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_directory_browsing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_directory_browsing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_dotnet_environment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_dotnet_environment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_dotnet_extensibility() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_dotnet_extensibility", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_freecell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_freecell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_ftp_extensibility() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_ftp_extensibility", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_ftp_server() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_ftp_server", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_ftp_service() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_ftp_service", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_games() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_games", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_health_and_diagnostics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_health_and_diagnostics", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_http_errors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_http_errors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_http_logging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_http_logging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_http_redirection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_http_redirection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_iis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_iis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_iis_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_iis_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_iis_client_certificate_mapping_authentication() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_iis_client_certificate_mapping_authentication", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_internet_backgammon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_internet_backgammon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_internet_checkers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_internet_checkers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_internet_explorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_internet_explorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_internet_explorer_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_internet_explorer_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_internet_games() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_internet_games", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_internet_information_services() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_internet_information_services", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_internet_printing_client() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_internet_printing_client", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_internet_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_internet_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_ip_security() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_ip_security", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_isapi_extensions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_isapi_extensions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_isapi_filters() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_isapi_filters", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_logging_tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_logging_tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_lpd_print_service() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_lpd_print_service", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_lpr_port_monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_lpr_port_monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_mahjong_titans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_mahjong_titans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_media_features() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_media_features", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_microsoft_dotnet_framework() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_microsoft_dotnet_framework", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_microsoft_message_queue__msmq__server() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_microsoft_message_queue__msmq__server", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_minesweeper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_minesweeper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_more_games() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_more_games", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_msmq_active_directory_domain_services_integration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_msmq_active_directory_domain_services_integration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_msmq_dcom_proxy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_msmq_dcom_proxy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_msmq_http_support() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_msmq_http_support", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_msmq_triggers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_msmq_triggers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_multicasting_support() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_multicasting_support", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_odbc_logging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_odbc_logging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_performance_features() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_performance_features", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_print_and_document_services() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_print_and_document_services", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_process_model() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_process_model", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_purble_place() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_purble_place", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_ras_connection_manager_administration_kit__cmak_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_ras_connection_manager_administration_kit__cmak_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_remote_differential_compression() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_remote_differential_compression", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_request_filtering() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_request_filtering", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_request_monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_request_monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_rip_listener() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_rip_listener", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_scan_management() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_scan_management", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_search_tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_search_tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_security() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_security", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_server_side_includes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_server_side_includes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_services_for_nfs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_services_for_nfs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_simple_network_management_protocol__snmp_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_simple_network_management_protocol__snmp_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_simple_tcpip_services() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_simple_tcpip_services", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_solitaire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_solitaire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_spider_solitaire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_spider_solitaire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_static_content() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_static_content", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_subsystem_for_unix_based_applications() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_subsystem_for_unix_based_applications", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_tablet_pc_components() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_tablet_pc_components", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_telnet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_telnet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_tftp_client() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_tftp_client", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_tracing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_tracing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_url_authorization() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_url_authorization", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_web_management_tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_web_management_tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_webdav_publishing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_webdav_publishing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_authentication() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_authentication", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_communication_foundation_http_activation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_communication_foundation_http_activation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_communication_foundation_non_http_activation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_communication_foundation_non_http_activation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_dvd_maker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_dvd_maker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_fax_and_scan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_fax_and_scan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_gadget_platform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_gadget_platform", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_media_center() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_media_center", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_media_player() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_media_player", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_process_activation_service() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_process_activation_service", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_windows_tiff_ifilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_windows_tiff_ifilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_world_wide_web_services() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_world_wide_web_services", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feature_xps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feature_xps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property load_driver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load_driver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property load_feature() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load_feature", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property load_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property move() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("move", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chess Titans|Games
        '''FreeCell|Games
        '''Hearts|Games
        '''Internet Games|Games
        '''Internet Backgammon|Internet Games
        '''Internet Checkers|Internet Games
        '''Internet Spades|Internet Games
        '''Mahjong Titans|Games
        '''Minesweeper|Games
        '''More Games|Games
        '''Purble Place|Games
        '''Solitaire|Games
        '''Spider Solitaire|Games
        '''OEMHelpCustomization|Help
        '''CorporationHelpCustomization|Help
        '''FTP Server|Internet Information Services
        '''FTP Extensibility|FTP Server
        '''FTP Service|FTP Server
        '''Web Management Tools|Internet Information Services
        '''IIS 6 Ma [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ParentFeatureList() As String
            Get
                Return ResourceManager.GetString("ParentFeatureList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;wWHloLDQih6mzKql+oyEbFaL5yJqm31O+gxqLXplEJpGuJjBVeoKmQM8yDEzm8Cv7Vnggu+md3garZvuJlfdFLzBYDMSGWTRkpuMF2mYpLcnCRKD4KRNVvAQv6orTWwKi9Ndp3PE9eOmWD42piHaRc8045G7DwH8+NagoTUXOhNKYjx0+nOQi6+wmXrNleGnDEO9izvlq4WaPY10FBZWEQgOx7xhXaSmCwaNLZUeqmp8IZQEPXHjLMburTJybh26eIi9Pix6ajVmrUtkUbm4lSavAqxpCBd8EBTaC7mhJX9VBWd5SMVJgt8Mb4+6BERfkGXgS61A4qmqhsEUk1IOO8k3uWOMOaUTuLYSPrfFPC6qDW2rt/HweMtUFoknbQH1IsjAfoOmdRzR29Pq1D0ysLmohpBMG7PpKpmQR8E0tlM8U+CckgfWP8NvGL7LOTEIWi5VOB1FICwRwIOKlRUMFjXHqXxdneby/MlcMyqjRq [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property pubkey() As String
            Get
                Return ResourceManager.GetString("pubkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FTP Extensibility|FTP Service
        '''Windows Media Center|Windows Media Player
        '''IIS 6 Management Console|IIS Metabase and IIS 6 configuration compatibility
        '''IIS 6 Scripting Tools|IIS 6 WMI Compatibility;IIS Metabase and IIS 6 configuration compatibility
        '''.NET Extensibility|Request Filtering
        '''ASP|ISAPI Extensions;Request Filtering
        '''ASP.NET|.NET Extensibility;ISAPI Extensions;ISAPI Filters;Default Document;Request Filtering
        '''WebDAV Publishing|Static Content
        '''Windows Communication Foundation HTTP Activation|.NET Ext [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RequiredFeatureList() As String
            Get
                Return ResourceManager.GetString("RequiredFeatureList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property u_a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("u_a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property u_i() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("u_i", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property u_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("u_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property u_p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("u_p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property u_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("u_u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_cab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_cab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_mlc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_mlc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_wusa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_wusa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
